export const DOG_BREEDS = [
  'Mixed Breed','Multiple Breeds',
  'Affenpinscher','Afghan Hound','Airedale Terrier','Akita','Akita (Japanese)',
  'Alaskan Malamute','American Hairless Terrier','American Staffordshire Terrier',
  'Anatolian Shepherd Dog','Australasian Bosdog','Australian Cattle Dog',
  'Australian Kelpie','Australian Shepherd','Australian Silky Terrier',
  'Australian Stumpy Tail Cattle Dog','Australian Terrier','Azawakh','Basenji',
  'Basset Fauve de Bretagne','Basset Hound','Bavarian Mountain Scent Hound',
  'Beagle','Bearded Collie','Beauceron','Bedlington Terrier',
  'Belgian Shepherd Dog (Groenendael)','Belgian Shepherd Dog (Laekenois)',
  'Belgian Shepherd Dog (Malinois)','Belgian Shepherd Dog (Tervueren)',
  'Bergamasco Shepherd Dog','Bernese Mountain Dog','Bichon Frise','Biewer Terrier',
  'Black and Tan Coonhound','Bloodhound','Bluetick Coonhound','Bolognese',
  'Border Collie','Border Terrier','Borzoi','Boston Terrier','Bouvier des Flandres',
  'Boxer','Bracco Italiano','Briard','British Bulldog','Brittany','Bull Terrier',
  'Bull Terrier (Miniature)','Bullmastiff','Cairn Terrier','Canaan Dog',
  'Canadian Eskimo Dog','Cane Corso','Caucasian Shepherd Dog',
  'Cavalier King Charles Spaniel','Central Asian Shepherd Dog','Cesky Terrier',
  'Chesapeake Bay Retriever','Chihuahua (Long Coat)','Chihuahua (Smooth Coat)',
  'Chinese Crested Dog','Chow Chow','Cirneco Dell\'Etna','Clumber Spaniel',
  'Cocker Spaniel','Cocker Spaniel (American)','Collie (Rough)','Collie (Smooth)',
  'Coton De Tulear','Curly Coated Retriever','Dachshund (Long Haired)',
  'Dachshund (Miniature Long Haired)','Dachshund (Miniature Smooth Haired)',
  'Dachshund (Miniature Wire Haired)','Dachshund (Rabbit Long Haired)',
  'Dachshund (Rabbit Smooth Haired)','Dachshund (Rabbit Wire Haired)',
  'Dachshund (Smooth Haired)','Dachshund (Wire Haired)','Dalmatian',
  'Dandie Dinmont Terrier','Deerhound','Dobermann','Dogue de Bordeaux',
  'Dutch Shepherd Dog','English Setter','English Springer Spaniel',
  'English Toy Terrier (Black and Tan)','Estrela Mountain Dog','Eurasier',
  'Field Spaniel','Finnish Lapphund','Finnish Spitz','Flat Coated Retriever',
  'Fox Terrier (Smooth)','Fox Terrier (Wire)','Foxhound','French Bulldog',
  'German Hunting Terrier','German Pinscher','German Shepherd Dog',
  'German Shepherd Dog (Long Stock Coat)','German Shorthaired Pointer',
  'German Spitz (Klein)','German Spitz (Mittel)','German Wirehaired Pointer',
  'Glen of Imaal Terrier','Golden Retriever','Gordon Setter',
  'Grand Basset Griffon Vendeen','Great Dane','Great Swiss Mountain Dog',
  'Greyhound','Griffon Bruxellois','Hamiltonstovare','Harrier','Havanese',
  'Hungarian Vizsla','Hungarian Wirehaired Vizsla','Ibizan Hound',
  'Icelandic Sheepdog','Irish Red and White Setter','Irish Setter','Irish Terrier',
  'Irish Water Spaniel','Irish Wolfhound','Italian Greyhound','Italian Spinone',
  'Jack Russell Terrier','Japanese Chin','Japanese Spitz','Kangal Shepherd Dog',
  'Karelian Bear Dog','Keeshond','Kerry Blue Terrier','King Charles Spaniel',
  'Kleine Munsterlander','Komondor','Kuvasz','Labrador Retriever',
  'Lagotto Romagnolo','Lakeland Terrier','Landseer (European Continental Type)',
  'Large Munsterlander','Leonberger','Lhasa Apso','Lowchen','Maltese',
  'Manchester Terrier','Maremma Sheepdog','Mastiff','Miniature American Shepherd',
  'Miniature Pinscher','Mudi','Murray River Retriever','Neapolitan Mastiff',
  'Newfoundland','Norfolk Terrier','Norwegian Buhund','Norwegian Elkhound',
  'Norwich Terrier','Nova Scotia Duck Tolling Retriever','Old English Sheepdog',
  'Otterhound','Papillon','Parson Russell Terrier','Pekingese',
  'Peruvian Hairless Dog (Large)','Peruvian Hairless Dog (Medium)',
  'Peruvian Hairless Dog (Small)','Petit Basset Griffon Vendeen','Pharaoh Hound',
  'Pointer','Polish Lowland Sheepdog','Pomeranian','Poodle (Miniature)',
  'Poodle (Standard)','Poodle (Toy)','Porcelaine',
  'Portuguese Podengo (Large Smooth Haired)','Portuguese Podengo (Large Wire Haired)',
  'Portuguese Podengo (Medium Smooth Haired)','Portuguese Podengo (Medium Wire Haired)',
  'Portuguese Podengo (Small Smooth Haired)','Portuguese Podengo (Small Wire Haired)',
  'Portuguese Water Dog','Prague Ratter','Pug','Puli','Pumi','Pyrenean Mastiff',
  'Pyrenean Mountain Dog','Pyrenean Sheepdog Longhaired','Rhodesian Ridgeback',
  'Rottweiler','Russian Black Terrier','Russian Toy (Long Haired)',
  'Russian Toy (Smooth Haired)','Saluki','Samoyed','Schipperke','Schnauzer',
  'Schnauzer (Giant)','Schnauzer (Miniature)','Scottish Terrier','Sealyham Terrier',
  'Shar Pei','Shetland Sheepdog','Shiba Inu','Shih Tzu','Shikoku','Siberian Husky',
  'Skye Terrier','Sloughi','Soft Coated Wheaten Terrier','Spanish Mastiff',
  'Spanish Water Dog','St Bernard','Staffordshire Bull Terrier','Sussex Spaniel',
  'Swedish Lapphund','Swedish Vallhund','Tatra Shepherd Dog','Tenterfield Terrier',
  'Tibetan Mastiff','Tibetan Spaniel','Tibetan Terrier','Tornjak','Weimaraner',
  'Weimaraner (Long-haired)','Welsh Corgi (Cardigan)','Welsh Corgi (Pembroke)',
  'Welsh Springer Spaniel','Welsh Terrier','West Highland White Terrier','Whippet',
  'White Swiss Shepherd Dog','Wirehaired Slovakian Pointer',
  'Xoloitzcuintle (Intermediate)','Xoloitzcuintle (Miniature)',
  'Xoloitzcuintle (Standard)','Yakutian Laika','Yorkshire Terrier',
];

// Alternate words people search for when their dog isn't a single recognised
// breed, so "mutt" or "moggy" still surfaces the "Mixed Breed" suggestion.
const BREED_SYNONYMS = {
  'Mixed Breed': ['mutt', 'mongrel', 'moggy', 'moggie', 'cross', 'crossbreed', 'cross breed', 'cross-breed'],
  'Multiple Breeds': ['multiple dogs', 'two dogs', 'several dogs', 'group photo', 'more than one dog'],
};

export function searchBreeds(query, limit = 60) {
  const q = (query || '').trim().toLowerCase();
  if (!q) return DOG_BREEDS.slice(0, 8);
  return DOG_BREEDS
    .filter(b => b.toLowerCase().includes(q) || (BREED_SYNONYMS[b] || []).some(s => s.includes(q)))
    .slice(0, limit);
}
